// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_Panel5;
lv_obj_t * ui_battery_indicator;
lv_obj_t * ui_battery_level;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_Container1;
lv_obj_t * ui_Power;
lv_obj_t * ui_Container2;
lv_obj_t * ui_watt;
lv_obj_t * ui_Image1;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_Volt;
lv_obj_t * ui_volttext;
lv_obj_t * ui_Panel7;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_Time;
lv_obj_t * ui_Time1;
lv_obj_t * ui_Image2;
lv_obj_t * ui_Panel9;
void ui_event_Button1(lv_event_t * e);
lv_obj_t * ui_Button1;
lv_obj_t * ui_Image5;
lv_obj_t * ui_Temp;
lv_obj_t * ui_Image3;
lv_obj_t * ui_Panel4;
lv_obj_t * ui_Amp;
lv_obj_t * ui_amptext;
lv_obj_t * ui_Panel8;


// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
lv_obj_t * ui_Screen2;
void ui_event_ImgButton6(lv_event_t * e);
lv_obj_t * ui_ImgButton6;
lv_obj_t * ui_Container3;
void ui_event_USBC(lv_event_t * e);
lv_obj_t * ui_USBC;
lv_obj_t * ui_Switch2;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Image6;
lv_obj_t * ui_Label4;
void ui_event_ACOutput(lv_event_t * e);
lv_obj_t * ui_ACOutput;
lv_obj_t * ui_Switch3;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Image7;
lv_obj_t * ui_Label6;
void ui_event_DCOutput(lv_event_t * e);
lv_obj_t * ui_DCOutput;
lv_obj_t * ui_Switch4;
lv_obj_t * ui_Label7;
lv_obj_t * ui_Image8;
lv_obj_t * ui_Label8;
void ui_event_USBA(lv_event_t * e);
lv_obj_t * ui_USBA;
lv_obj_t * ui_Switch5;
lv_obj_t * ui_Label9;
lv_obj_t * ui_Image9;
lv_obj_t * ui_Label10;
void ui_event_Fan(lv_event_t * e);
lv_obj_t * ui_Fan;
lv_obj_t * ui_Switch6;
lv_obj_t * ui_Label11;
lv_obj_t * ui_Image10;
lv_obj_t * ui_Label12;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_arrow[1] = {&ui_img_arrow1_png};
const lv_img_dsc_t * ui_imgset_rectangle_[2] = {&ui_img_rectangle_12_png, &ui_img_rectangle_9_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_OVER_LEFT, 200, 0, &ui_Screen2_screen_init);
    }
}
void ui_event_ImgButton6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 200, 0, &ui_Screen1_screen_init);
    }
}
// void ui_event_USBC(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     lv_obj_t * target = lv_event_get_target(e);
//     if(event_code == LV_EVENT_CLICKED) {
//         _ui_state_modify(ui_Switch2, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
//         _ui_checked_set_text_value(ui_Label3, target, "ON", "OFF");
//         toggleusbc(e);
//     }
// }
// void ui_event_ACOutput(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     lv_obj_t * target = lv_event_get_target(e);
//     if(event_code == LV_EVENT_CLICKED) {
//         _ui_state_modify(ui_Switch3, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
//         _ui_checked_set_text_value(ui_Label5, target, "ON", "OFF");
//         toggleac(e);
//     }
// }
// void ui_event_DCOutput(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     lv_obj_t * target = lv_event_get_target(e);
//     if(event_code == LV_EVENT_CLICKED) {
//         _ui_state_modify(ui_Switch4, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
//         _ui_checked_set_text_value(ui_Label7, target, "ON", "OFF");
//         toggledc(e);
//     }
// }
// void ui_event_USBA(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     lv_obj_t * target = lv_event_get_target(e);
//     if(event_code == LV_EVENT_CLICKED) {
//         _ui_state_modify(ui_Switch5, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
//         _ui_checked_set_text_value(ui_Label9, target, "ON", "OFF");
//         toggleusba(e);
//     }
// }
// void ui_event_Fan(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     lv_obj_t * target = lv_event_get_target(e);
//     if(event_code == LV_EVENT_CLICKED) {
//         _ui_state_modify(ui_Switch6, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
//         _ui_checked_set_text_value(ui_Label11, target, "ON", "OFF");
//         togglefan(e);
//     }
// }

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui_Screen2_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
