// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_battery_indicator;
extern lv_obj_t * ui_battery_level;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Power;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_watt;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Volt;
extern lv_obj_t * ui_volttext;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Time;
extern lv_obj_t * ui_Time1;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Panel9;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Temp;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Amp;
extern lv_obj_t * ui_amptext;
extern lv_obj_t * ui_Panel8;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
void ui_event_ImgButton6(lv_event_t * e);
extern lv_obj_t * ui_ImgButton6;
extern lv_obj_t * ui_Container3;
void ui_event_USBC(lv_event_t * e);
extern lv_obj_t * ui_USBC;
extern lv_obj_t * ui_Switch2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Label4;
void ui_event_ACOutput(lv_event_t * e);
extern lv_obj_t * ui_ACOutput;
extern lv_obj_t * ui_Switch3;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Label6;
void ui_event_DCOutput(lv_event_t * e);
extern lv_obj_t * ui_DCOutput;
extern lv_obj_t * ui_Switch4;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_Label8;
void ui_event_USBA(lv_event_t * e);
extern lv_obj_t * ui_USBA;
extern lv_obj_t * ui_Switch5;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_Label10;
void ui_event_Fan(lv_event_t * e);
extern lv_obj_t * ui_Fan;
extern lv_obj_t * ui_Switch6;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_power_png);    // assets/power.png
LV_IMG_DECLARE(ui_img_clock_png);    // assets/clock.png
LV_IMG_DECLARE(ui_img_533029405);    // assets/power-button-off.png
LV_IMG_DECLARE(ui_img_celsius_png);    // assets/celsius.png
LV_IMG_DECLARE(ui_img_arrow_png);    // assets/arrow.png
LV_IMG_DECLARE(ui_img_arrow1_png);    // assets/arrow1.png
LV_IMG_DECLARE(ui_img_rectangle_9_png);    // assets/Rectangle 9.png
LV_IMG_DECLARE(ui_img_rectangle_12_png);    // assets/Rectangle 12.png
LV_IMG_DECLARE(ui_img_usbc_png);    // assets/usbc.png
LV_IMG_DECLARE(ui_img_outlet_png);    // assets/outlet.png
LV_IMG_DECLARE(ui_img_electricity_png);    // assets/electricity.png
LV_IMG_DECLARE(ui_img_charger_png);    // assets/charger.png
LV_IMG_DECLARE(ui_img_2092181609);    // assets/exhaust-fan.png



LV_FONT_DECLARE(ui_font_ABR20);
LV_FONT_DECLARE(ui_font_ABR22);
LV_FONT_DECLARE(ui_font_digital140);
LV_FONT_DECLARE(ui_font_digital160);
LV_FONT_DECLARE(ui_font_digital50);
LV_FONT_DECLARE(ui_font_digital_60);
LV_FONT_DECLARE(ui_font_digital_80);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
