// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void toggleusbc(lv_event_t * e);
void toggleac(lv_event_t * e);
void toggledc(lv_event_t * e);
void toggleusba(lv_event_t * e);
void togglefan(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
