// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void toggleusbc(lv_event_t * e)
{
	// Your code here
}

void toggleac(lv_event_t * e)
{
	// Your code here
}

void toggledc(lv_event_t * e)
{
	// Your code here
}

void toggleusba(lv_event_t * e)
{
	// Your code here
}

void togglefan(lv_event_t * e)
{
	// Your code here
}
