// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgButton6 = lv_imgbtn_create(ui_Screen2);
    lv_imgbtn_set_src(ui_ImgButton6, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_arrow_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton6, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_arrow1_png, NULL);
    lv_obj_set_height(ui_ImgButton6, 64);
    lv_obj_set_width(ui_ImgButton6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButton6, -355);
    lv_obj_set_y(ui_ImgButton6, -192);
    lv_obj_set_align(ui_ImgButton6, LV_ALIGN_CENTER);

    ui_Container3 = lv_obj_create(ui_Screen2);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, 660);
    lv_obj_set_height(ui_Container3, 430);
    lv_obj_set_x(ui_Container3, 31);
    lv_obj_set_y(ui_Container3, 0);
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_USBC = lv_imgbtn_create(ui_Container3);
    lv_imgbtn_set_src(ui_USBC, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_rectangle_9_png, NULL);
    lv_imgbtn_set_src(ui_USBC, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_rectangle_12_png, NULL);
    lv_imgbtn_set_src(ui_USBC, LV_IMGBTN_STATE_DISABLED, NULL, &ui_img_rectangle_9_png, NULL);
    lv_imgbtn_set_src(ui_USBC, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_rectangle_12_png, NULL);
    lv_imgbtn_set_src(ui_USBC, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_rectangle_12_png, NULL);
    lv_imgbtn_set_src(ui_USBC, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui_img_rectangle_9_png, NULL);
    lv_obj_set_height(ui_USBC, 200);
    lv_obj_set_width(ui_USBC, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_align(ui_USBC, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_USBC, LV_OBJ_FLAG_CHECKABLE);     /// Flags

    ui_Switch2 = lv_switch_create(ui_USBC);
    lv_obj_set_width(ui_Switch2, 60);
    lv_obj_set_height(ui_Switch2, 30);
    lv_obj_set_x(ui_Switch2, -20);
    lv_obj_set_y(ui_Switch2, 15);
    lv_obj_set_align(ui_Switch2, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_Switch2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_bg_color(ui_Switch2, lv_color_hex(0x4F4D5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Switch2, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Switch2, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_Switch2, lv_color_hex(0xD909FE), LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Switch2, 255, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_color(ui_Switch2, lv_color_hex(0x2096FF), LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_bg_main_stop(ui_Switch2, 0, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_stop(ui_Switch2, 255, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_dir(ui_Switch2, LV_GRAD_DIR_HOR, LV_PART_KNOB | LV_STATE_CHECKED);

    ui_Label3 = lv_label_create(ui_USBC);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 30);
    lv_obj_set_y(ui_Label3, 20);
    lv_label_set_text(ui_Label3, "OFF");
    lv_obj_set_style_text_font(ui_Label3, &ui_font_ABR22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image6 = lv_img_create(ui_USBC);
    lv_img_set_src(ui_Image6, &ui_img_usbc_png);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 80
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 80
    lv_obj_set_x(ui_Image6, 0);
    lv_obj_set_y(ui_Image6, 10);
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label4 = lv_label_create(ui_USBC);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 0);
    lv_obj_set_y(ui_Label4, -15);
    lv_obj_set_align(ui_Label4, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Label4, "USB C");
    lv_obj_set_style_text_font(ui_Label4, &ui_font_ABR20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ACOutput = lv_imgbtn_create(ui_Container3);
    lv_imgbtn_set_src(ui_ACOutput, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_rectangle_9_png, NULL);
    lv_imgbtn_set_src(ui_ACOutput, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_rectangle_12_png, NULL);
    lv_imgbtn_set_src(ui_ACOutput, LV_IMGBTN_STATE_DISABLED, NULL, &ui_img_rectangle_9_png, NULL);
    lv_imgbtn_set_src(ui_ACOutput, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_rectangle_12_png, NULL);
    lv_imgbtn_set_src(ui_ACOutput, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_rectangle_12_png, NULL);
    lv_imgbtn_set_src(ui_ACOutput, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui_img_rectangle_9_png, NULL);
    lv_obj_set_height(ui_ACOutput, 200);
    lv_obj_set_width(ui_ACOutput, LV_SIZE_CONTENT);   /// 200
    lv_obj_add_flag(ui_ACOutput, LV_OBJ_FLAG_CHECKABLE);     /// Flags

    ui_Switch3 = lv_switch_create(ui_ACOutput);
    lv_obj_set_width(ui_Switch3, 60);
    lv_obj_set_height(ui_Switch3, 30);
    lv_obj_set_x(ui_Switch3, -20);
    lv_obj_set_y(ui_Switch3, 15);
    lv_obj_set_align(ui_Switch3, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_Switch3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_bg_color(ui_Switch3, lv_color_hex(0x4F4D5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Switch3, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Switch3, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_Switch3, lv_color_hex(0xD909FE), LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Switch3, 255, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_color(ui_Switch3, lv_color_hex(0x2096FF), LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_bg_main_stop(ui_Switch3, 0, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_stop(ui_Switch3, 255, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_dir(ui_Switch3, LV_GRAD_DIR_HOR, LV_PART_KNOB | LV_STATE_CHECKED);

    ui_Label5 = lv_label_create(ui_ACOutput);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 30);
    lv_obj_set_y(ui_Label5, 20);
    lv_label_set_text(ui_Label5, "OFF");
    lv_obj_set_style_text_font(ui_Label5, &ui_font_ABR22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image7 = lv_img_create(ui_ACOutput);
    lv_img_set_src(ui_Image7, &ui_img_outlet_png);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 80
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 80
    lv_obj_set_x(ui_Image7, 0);
    lv_obj_set_y(ui_Image7, 10);
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label6 = lv_label_create(ui_ACOutput);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 0);
    lv_obj_set_y(ui_Label6, -15);
    lv_obj_set_align(ui_Label6, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Label6, "AC Output");
    lv_obj_set_style_text_font(ui_Label6, &ui_font_ABR20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DCOutput = lv_imgbtn_create(ui_Container3);
    lv_imgbtn_set_src(ui_DCOutput, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_rectangle_9_png, NULL);
    lv_imgbtn_set_src(ui_DCOutput, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_rectangle_12_png, NULL);
    lv_imgbtn_set_src(ui_DCOutput, LV_IMGBTN_STATE_DISABLED, NULL, &ui_img_rectangle_9_png, NULL);
    lv_imgbtn_set_src(ui_DCOutput, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_rectangle_12_png, NULL);
    lv_imgbtn_set_src(ui_DCOutput, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_rectangle_12_png, NULL);
    lv_imgbtn_set_src(ui_DCOutput, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui_img_rectangle_9_png, NULL);
    lv_obj_set_height(ui_DCOutput, 200);
    lv_obj_set_width(ui_DCOutput, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_align(ui_DCOutput, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_DCOutput, LV_OBJ_FLAG_CHECKABLE);     /// Flags

    ui_Switch4 = lv_switch_create(ui_DCOutput);
    lv_obj_set_width(ui_Switch4, 60);
    lv_obj_set_height(ui_Switch4, 30);
    lv_obj_set_x(ui_Switch4, -20);
    lv_obj_set_y(ui_Switch4, 15);
    lv_obj_set_align(ui_Switch4, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_Switch4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_bg_color(ui_Switch4, lv_color_hex(0x4F4D5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Switch4, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Switch4, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_Switch4, lv_color_hex(0xD909FE), LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Switch4, 255, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_color(ui_Switch4, lv_color_hex(0x2096FF), LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_bg_main_stop(ui_Switch4, 0, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_stop(ui_Switch4, 255, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_dir(ui_Switch4, LV_GRAD_DIR_HOR, LV_PART_KNOB | LV_STATE_CHECKED);

    ui_Label7 = lv_label_create(ui_DCOutput);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 30);
    lv_obj_set_y(ui_Label7, 20);
    lv_label_set_text(ui_Label7, "OFF");
    lv_obj_set_style_text_font(ui_Label7, &ui_font_ABR22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image8 = lv_img_create(ui_DCOutput);
    lv_img_set_src(ui_Image8, &ui_img_electricity_png);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 80
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 80
    lv_obj_set_x(ui_Image8, 0);
    lv_obj_set_y(ui_Image8, 10);
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label8 = lv_label_create(ui_DCOutput);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 0);
    lv_obj_set_y(ui_Label8, -15);
    lv_obj_set_align(ui_Label8, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Label8, "DC Output");
    lv_obj_set_style_text_font(ui_Label8, &ui_font_ABR20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_USBA = lv_imgbtn_create(ui_Container3);
    lv_imgbtn_set_src(ui_USBA, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_rectangle_9_png, NULL);
    lv_imgbtn_set_src(ui_USBA, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_rectangle_12_png, NULL);
    lv_imgbtn_set_src(ui_USBA, LV_IMGBTN_STATE_DISABLED, NULL, &ui_img_rectangle_9_png, NULL);
    lv_imgbtn_set_src(ui_USBA, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_rectangle_12_png, NULL);
    lv_imgbtn_set_src(ui_USBA, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_rectangle_12_png, NULL);
    lv_imgbtn_set_src(ui_USBA, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui_img_rectangle_9_png, NULL);
    lv_obj_set_height(ui_USBA, 200);
    lv_obj_set_width(ui_USBA, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_align(ui_USBA, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_USBA, LV_OBJ_FLAG_CHECKABLE);     /// Flags

    ui_Switch5 = lv_switch_create(ui_USBA);
    lv_obj_set_width(ui_Switch5, 60);
    lv_obj_set_height(ui_Switch5, 30);
    lv_obj_set_x(ui_Switch5, -20);
    lv_obj_set_y(ui_Switch5, 15);
    lv_obj_set_align(ui_Switch5, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_Switch5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_bg_color(ui_Switch5, lv_color_hex(0x4F4D5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Switch5, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Switch5, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_Switch5, lv_color_hex(0xD909FE), LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Switch5, 255, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_color(ui_Switch5, lv_color_hex(0x2096FF), LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_bg_main_stop(ui_Switch5, 0, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_stop(ui_Switch5, 255, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_dir(ui_Switch5, LV_GRAD_DIR_HOR, LV_PART_KNOB | LV_STATE_CHECKED);

    ui_Label9 = lv_label_create(ui_USBA);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, 30);
    lv_obj_set_y(ui_Label9, 20);
    lv_label_set_text(ui_Label9, "OFF");
    lv_obj_set_style_text_font(ui_Label9, &ui_font_ABR22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image9 = lv_img_create(ui_USBA);
    lv_img_set_src(ui_Image9, &ui_img_charger_png);
    lv_obj_set_width(ui_Image9, LV_SIZE_CONTENT);   /// 80
    lv_obj_set_height(ui_Image9, LV_SIZE_CONTENT);    /// 80
    lv_obj_set_x(ui_Image9, 0);
    lv_obj_set_y(ui_Image9, 10);
    lv_obj_set_align(ui_Image9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image9, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label10 = lv_label_create(ui_USBA);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, 0);
    lv_obj_set_y(ui_Label10, -15);
    lv_obj_set_align(ui_Label10, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Label10, "USB A");
    lv_obj_set_style_text_font(ui_Label10, &ui_font_ABR20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Fan = lv_imgbtn_create(ui_Container3);
    lv_imgbtn_set_src(ui_Fan, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_rectangle_9_png, NULL);
    lv_imgbtn_set_src(ui_Fan, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_rectangle_12_png, NULL);
    lv_imgbtn_set_src(ui_Fan, LV_IMGBTN_STATE_DISABLED, NULL, &ui_img_rectangle_9_png, NULL);
    lv_imgbtn_set_src(ui_Fan, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_rectangle_12_png, NULL);
    lv_imgbtn_set_src(ui_Fan, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_rectangle_12_png, NULL);
    lv_imgbtn_set_src(ui_Fan, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui_img_rectangle_9_png, NULL);
    lv_obj_set_height(ui_Fan, 200);
    lv_obj_set_width(ui_Fan, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_align(ui_Fan, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_Fan, LV_OBJ_FLAG_CHECKABLE);     /// Flags

    ui_Switch6 = lv_switch_create(ui_Fan);
    lv_obj_set_width(ui_Switch6, 60);
    lv_obj_set_height(ui_Switch6, 30);
    lv_obj_set_x(ui_Switch6, -20);
    lv_obj_set_y(ui_Switch6, 15);
    lv_obj_set_align(ui_Switch6, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_Switch6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_bg_color(ui_Switch6, lv_color_hex(0x4F4D5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Switch6, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Switch6, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_Switch6, lv_color_hex(0xD909FE), LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Switch6, 255, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_color(ui_Switch6, lv_color_hex(0x2096FF), LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_bg_main_stop(ui_Switch6, 0, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_stop(ui_Switch6, 255, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_dir(ui_Switch6, LV_GRAD_DIR_HOR, LV_PART_KNOB | LV_STATE_CHECKED);

    ui_Label11 = lv_label_create(ui_Fan);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, 30);
    lv_obj_set_y(ui_Label11, 20);
    lv_label_set_text(ui_Label11, "OFF");
    lv_obj_set_style_text_font(ui_Label11, &ui_font_ABR22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image10 = lv_img_create(ui_Fan);
    lv_img_set_src(ui_Image10, &ui_img_2092181609);
    lv_obj_set_width(ui_Image10, LV_SIZE_CONTENT);   /// 80
    lv_obj_set_height(ui_Image10, LV_SIZE_CONTENT);    /// 80
    lv_obj_set_x(ui_Image10, 0);
    lv_obj_set_y(ui_Image10, 10);
    lv_obj_set_align(ui_Image10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image10, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label12 = lv_label_create(ui_Fan);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, 0);
    lv_obj_set_y(ui_Label12, -15);
    lv_obj_set_align(ui_Label12, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Label12, "Fan");
    lv_obj_set_style_text_font(ui_Label12, &ui_font_ABR20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ImgButton6, ui_event_ImgButton6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_USBC, ui_event_USBC, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ACOutput, ui_event_ACOutput, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DCOutput, ui_event_DCOutput, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_USBA, ui_event_USBA, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Fan, ui_event_Fan, LV_EVENT_ALL, NULL);

}
